# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4e04ea4c380e445cbbc4b954a249430abbfbc4236d570355e0b70889d90a7179b7fb05367565afc00a1ed18c7473130a8ebe79bd07fd1544bd57dacad9c4b234

test:
  secret_key_base: 4b8f494b78f40361f2ccc82a226d5e10138d9cd88e261f30d26c9f7e7e131b582d184ba2dfddb13b46f3088fb94dc3142e640085406112857d5644cf4ad0da31

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
